# Generated by Django 5.1.6 on 2025-11-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
