# Generated by Django 5.2.4 on 2025-11-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_device_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
