# Generated by Django 5.2.4 on 2025-11-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_device_is_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
